version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
  ignore:
    # ignore Maven APIs/SPIs
    - dependency-name: org.apache.maven:*
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "daily"
- package-ecosystem: "npm"
  directory: "/oldalbum.web.frontend/src/main/frontend/"
  schedule:
    interval: "daily"
