import { createAction } from '@reduxjs/toolkit';

export const SUCCESSFULL_CHANGE_OF_PASSWORD_REQUIREMENT = createAction('SUCCESSFULL_CHANGE_OF_PASSWORD_REQUIREMENT');
export const ADD_PICTURE_IMAGE_URL_SUCCESSFULLY_LOADED = createAction('ADD_PICTURE_IMAGE_URL_SUCCESSFULLY_LOADED');
export const ALBUM_SELECT_ALL = createAction('ALBUM_SELECT_ALL');
export const START_SELECTION_DOWNLOAD = createAction('START_SELECTION_DOWNLOAD');
export const SELECT_LOCALE = createAction('SELECT_LOCALE');
export const OPEN_WARNING_DIALOG_ENTRY_IS_PASSWORD_PROTECTED = createAction('OPEN_WARNING_DIALOG_ENTRY_IS_PASSWORD_PROTECTED');
export const CLOSE_WARNING_DIALOG_ENTRY_IS_PASSWORD_PROTECTED = createAction('CLOSE_WARNING_DIALOG_ENTRY_IS_PASSWORD_PROTECTED');
export const REMOVE_PASSWORD_PROTECTION_AND_CLOSE_WARNING_DIALOG = createAction('REMOVE_PASSWORD_PROTECTION_AND_CLOSE_WARNING_DIALOG');
export const SHARE_LINK = createAction('SHARE_LINK');
export const CLEAR_SHARED_LINK_ITEM = createAction('CLEAR_SHARED_LINK_ITEM');
